django/frag/frag/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('review/',include('review.urls')),
    path('quiz/',include('quiz.urls'))]

django/frag/review/urls.py
from django.urls import path,include
from . import views

app_name = 'reviews'

urlpatterns = [
    path('',views.ListReviews.as_view(),name='all'),
    path('new/',views.CreateReview.as_view(),name='create'),
    path('review/',views.SingleReview.as_view(),name='single') #slugify path part 8 3min
]

django/frag/review/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# might not need
from django import template
register = template.Library()

class Review(models.Model):
    name = models.CharField(max_length=500,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    rating = models.IntegerField(blank=True,choices=((1,1),(2,2),(3,3),(4,4),(5,5)))
    # rating_html = models.IntegerField
    average = models.ManyToManyField(User,through='ReviewMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        #self.rating_html = misaka.html(self.rating)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('review:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class ReviewMember(models.Model):
    review = models.ForeignKey(Review,on_delete=models.CASCADE,related_name='reviewer')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_review')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('review','user')

django/frag/review/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic

from review.models import Review,ReviewMember
from . import models

class CreateReview(LoginRequiredMixin,generic.CreateView):
    fields = ('name')
    model = Review

class SingleReview(generic.DetailView):
    model = Review

class ListReviews(generic.ListView):
    model = Review

django/frag/review/templates/review/review_base.html
{ % extends "base.html" %}
{% block content %}
<div class="review-page">
    <div class="container">
        <div class="row">
            {% block prereview %}{% endblock %}
            {% block review_content %}{% endblock %}
            {% block postreview %}{% endblock %}
        </div>

    </div>
</div>
{% endblock %}

django/frag/review/templates/review/review_detail.html
{% extends "review/review_base.html" %}
{% block prereview %}

<h1>{{review.name}}</h1>
<h2>Rating: {{review.average}}</h2>

<div class="content">

    <!-- {% if user in review.members %} part 7 @ 7-->
</div>

{% endblock %}

{% block review_content %}
<div class="col-md-8">
    {% if review.rating.count ==0 %}
    <h2>No fragrences reviewed yet.</h2>
    {% else %}
        {% for review in review.rating.all %}
            {% include "quiz/_quiz.html"}
        {% endfor %}
</div>

{% endblock %}

django/frag/review/templates/review/review_form.html
{% extends "review/review_base.html" %}
{% load bootstrap3 %}

{% block review_content %}
<h4>Here are your reviews</h4>

<form action="{% url 'review:create' %}" method="post" id='reviewForm'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary btn-large' value="Create">
</form>

{% endbloxk %}

django/frag/review/templates/review/review_list.html
{% extends "review/review_base.html" %}

{% block prereview %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!
            <a href="{% url 'quiz:for_user' username=user.username %}">
                @{{user.username}}
            </a>
        </h2>
        
        {% endif %}

        <h2>Reviews</h2>
        <p>Previously reviewed fragrences:</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'review:create' %}" class='btn btn-md btn-fill btn-warning'>
        <span class='glyphicon glyphicon-plus-sign'>Click to review another fragrence</span>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block review_content %}
<div class="col-md-8">
    <div class="list-review">
        {% for review in object_list %}
        <a class='list-review-item' href="{% url 'review:single' slug=review.slug %}">
            <h3 class='title list-review-item-heading'>{{review.name}}</h3>
            <div class="list-review-item-text container-fluid">
                {{review.rating|safe}} <!--rating_html might need swap-->
            </div>
        </a>
        {% endfor %}
    </div>
</div>



{% endblock %}